version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 2001:4860:4860::8888
      - 2606:4700:4700::1111
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "0.0.0.0:20080:80"
